### ISSUE TITLE
Nuclei error

### ISSUE THREAD

**Issue by Nithissh0708** [projectdiscovery/pd-actions#11]
Hi ,
When I run nuclei-templates ..it says no template found 
I used the nuclei -t nuclei-templates target .
It says no templates found 
How to scan all nuclei-templates ?

**Comment by fguisso** [comment]
1. Do you run `Download templates` step? --> `nuclei -update-templates`
2. You need the absolute path, probably `-t ./nuclei-templates`.
3. If you update the templates directory, you need to pass the actual directory like that `-t ./something/nuclei-templates`
