### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by SAGEof6iixPATHS** [projectdiscovery/pd-actions#9]
I have faced a issue that i cannot run a domain with many subdomains github action has a timeout i think so.,. I need to clean every file of output and obviously domain to run a scan on a different domain/target ( It uses the output files and include them in the next run )
I think you need to add a line to clear the file before the next run and comment it out so people can use them if they need to.

**Comment by ehsandeep** [comment]
Thank you for the suggestion @SAGEof6iixPATHS, it completely depends on what you trying to achieve with your workflow, cleaning the output file result into losing "**changed**" data capability from the previous scan, pd-action is just an example of what you can do, feel free to update your workflow for your specific need.

Also, we can use [discussions](https://github.com/projectdiscovery/pd-actions/discussions) board for similar things so others can learn from it as it will be up for always unlike GitHub issue which doesn't show up once we close the issue.

Thank you.
